DROP TABLE IF EXISTS ODONTOLOGO;
CREATE TABLE IF NOT EXISTS ODONTOLOGO (
    ID LONG AUTO_INCREMENT PRIMARY KEY,
    MATRICULA VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL
);

-- para test --
INSERT INTO ODONTOLOGO(MATRICULA, NOMBRE, APELLIDO) VALUES ('50001','Camilo','Zuluaga'),('50002', 'Maria', 'Sanabria');